### ISSUE TITLE
Contributing.md: Instructions not working

### ISSUE THREAD

**Issue by lrouhier** [spine-generic/data-multi-subject#13]
the command `git add yourusername git@github.com:yourusername/data-multi-subject.git` did not work with my username. 
I followed the download procedure from the main repo. I also tried with the forked repo to see it that changed anything.
return the error: `fatal: pathspec 'lrouhier' did not match any files`
Isn't that command supposed to be `git add origin git@github.com:yourusername/data-multi-subject.git` ?

**Comment by lrouhier** [comment]
or prehaps it is `git remote add youusername git@github.com:yourusername/data-multi-subject.git` ?

**Comment by jcohenadad** [comment]
@lrouhier I also experienced this issue, and @kousu is on holidays, so we need to figure out something else until this issue is resolved.

I was trying to re-do it _without_ going through the fork, but I experienced the following issue:
~~~
  Remote origin not usable by git-annex; setting annex-ignore
~~~
<details><summary>Full output</summary>

~~~
julien-macbook:~/temp/pouf $ git clone https://github.com/spine-generic/data-multi-subject.git
Cloning into 'data-multi-subject'...
remote: Enumerating objects: 26919, done.
remote: Counting objects: 100% (26919/26919), done.
remote: Compressing objects: 100% (14543/14543), done.
remote: Total 26919 (delta 8292), reused 26488 (delta 7881), pack-reused 0
Receiving objects: 100% (26919/26919), 2.70 MiB | 7.25 MiB/s, done.
Resolving deltas: 100% (8292/8292), done.
Checking out files: 100% (4353/4353), done.
julien-macbook:~/temp/pouf $ cd data-multi-subject/
julien-macbook:~/temp/pouf/data-multi-subject $ git annex init
init  (merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)

  Remote origin not usable by git-annex; setting annex-ignore
ok
(recording state in git...)
julien-macbook:~/temp/pouf/data-multi-subject $ git remote
origin
julien-macbook:~/temp/pouf/data-multi-subject $ git annex init &&
~~~

</details>

The `git remote` should show `amazon`, but it does not.

<details><summary>`git-annex` installed via brew</summary>

~~~
 git annex version
git-annex version: 8.20200810
build flags: Assistant Webapp Pairing WebDAV FsEvents TorrentParser MagicMime Feeds Testsuite
dependency versions: bloomfilter-2.0.1.0 cryptonite-0.27 DAV-1.3.4 feed-1.3.0.1 ghc-8.6.5 http-client-0.7.1 persistent-sqlite-2.10.6.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.1.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL X*
remote types: git gcrypt p2p bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: darwin x86_64
supported repository versions: 8
upgrade supported from repository versions: 0 1 2 3 4 5 6 7
local repository version: 8
~~~

</details>

**Comment by jcohenadad** [comment]
Weirdly, when I do the *exact same thing* on Linux, it works fine:
~~~
(base) [jcohen@gra-login3 data-multi-subject]$ git annex init
init  (merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)

  Remote origin not usable by git-annex; setting annex-ignore
(Auto enabling special remote amazon...)
ok
(recording state in git...)
(base) [jcohen@gra-login3 data-multi-subject]$ git remote
amazon --> 🎉
origin
~~~

**Comment by jcohenadad** [comment]
@kousu @drulex do you have any idea what's going on?

**Comment by lrouhier** [comment]
Using a fork, and downloading the data from the fork: 

git remote -v shows :
~~~
amazon
origin  https://github.com/lrouhier/data-multi-subject.git (fetch)
origin  https://github.com/lrouhier/data-multi-subject.git (push)
~~~
(I am on linux so that is probably it) 

git annex installed via conda

**Comment by jcohenadad** [comment]
@lrouhier does it work on your end with WSL?

**Comment by lrouhier** [comment]
Let me try with WSL, I am currently on Rosenberg (because the data is there).

**Comment by jcohenadad** [comment]
@lrouhier then, what happens if you do `git annex get sub-unf01`?

**Comment by Drulex** [comment]
> or prehaps it is `git remote add youusername git@github.com:yourusername/data-multi-subject.git` ?

Yes it's `git remote add`

**Comment by lrouhier** [comment]
If the folder is here --> nothing
If i remove it and then run git annex get sub-unf01 I get: 
~~~
$ git annex get sub-unf01
git-annex: sub-unf01 not found
git-annex: get: 1 failed
~~~

**Comment by lrouhier** [comment]
Thanks @Drulex let me try that again with a clean version then.

**Comment by lrouhier** [comment]
As long as we are talking about contributing.md: 
~~~
git add yourusername git@github.com:yourusername/data-multi-subject.git
git annex sync yourusername
~~~~

will work *only* if you are using ssh. If you are using https you should use `git remote add yourusername  https://github.com/yourusername/data-multi-subject.git`

**Comment by lrouhier** [comment]
So the issue seems to come from the `git add ` which should be `git remote add`.

**Comment by Drulex** [comment]
> will work _only_ if you are using ssh. If you are using https you should use `git remote add yourusername https://github.com/yourusername/data-multi-subject.git`

Yes. Always use ssh :closed_lock_with_key:

**Comment by jcohenadad** [comment]
@lrouhier can you please fix the documentation? thanks!

**Comment by kousu** [comment]
Sorry about that!

Looks like this was fixed in https://github.com/spine-generic/data-multi-subject/commit/7e55c36ae5f0cfaf6b0ae22b0f81e960c511a7ca#diff-6a3371457528722a734f3c51d9238c13 ?

This could be more reliable

```
git annex sync --content
```

but I am worried that might end up corrupting the metadata, especially if you have multiple forks involved so I didn't want to recommend it.

Think we can close this now?

**Comment by jcohenadad** [comment]
issue fixed
